#gerenciador_login:
#    pattern:  /admin/
#    defaults: { _controller: GerenciadorLoginBundle:Secured:login }
    
_admin:
    pattern: /
    defaults: { _controller: GerenciadorLoginBundle:Default:index }