Mercado\PaginaBundle\Entity\Empresa:
    type: entity
    table: null
    repositoryClass: Mercado\PaginaBundle\Entity\EmpresaRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
