parameters:
    database_driver: pdo_mysql
    database_host: mysql.mercadodesabores.com.br
    database_port: null
    database_name: mercadodesabor
    database_user: mercadodesabor
    database_password: z9z7h7
    database_path: null
    mailer_transport: gmail
    mailer_host: smtp.gmail.com
    mailer_user: diegogiacobbo@gmail.com
    mailer_password: oKXx9b7m
    mailer_port: 587
    mailer_encryption: ssl
    locale: en
    secret: 460ddf271d8ed00457e95224284285e37e323c8f
