mercado_pagina:
    resource: "@MercadoPaginaBundle/Resources/config/routing.yml"
    prefix:   /
#
#gerenciador_login:
#    resource: "@GerenciadorLoginBundle/Resources/config/routing.yml"
#    prefix:   /admin
#    
#gerenciador_login:
#    resource: "@GerenciadorLoginBundle/Resources/config/routing.yml"
#    prefix:   /admin/
    
_admin:
    resource: "@GerenciadorLoginBundle/Resources/config/routing.yml"
    prefix:   /admin/

_welcome:
    pattern:  /
    defaults: { _controller: MercadoPaginaBundle:Default:index }
    
_admin_secured:
    resource: "@GerenciadorLoginBundle/Controller/SecuredController.php"
    type:     annotation
    
    
MercadoPaginaBundle_admin_cidade:
    resource: "@MercadoPaginaBundle/Resources/config/routing/cidade.yml"
    prefix:   /admin/cidade
    
_admin_cidade:
    resource: "@MercadoPaginaBundle/Controller/CidadeController.php"
    type:     annotation


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
