parameters:
#    mercado_pagina.example.class: Mercado\PaginaBundle\Example

services:
#    mercado_pagina.example:
#        class: %mercado_pagina.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
