<?php

namespace Proxies\__CG__\Mercado\PaginaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contato extends \Mercado\PaginaBundle\Entity\Contato implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getContato()
    {
        $this->__load();
        return parent::getContato();
    }

    public function setContato($contato)
    {
        $this->__load();
        return parent::setContato($contato);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }

    public function getData()
    {
        $this->__load();
        return parent::getData();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmailSecundario($emailSecundario)
    {
        $this->__load();
        return parent::setEmailSecundario($emailSecundario);
    }

    public function getEmailSecundario()
    {
        $this->__load();
        return parent::getEmailSecundario();
    }

    public function setTelefoneResidencial($telefoneResidencial)
    {
        $this->__load();
        return parent::setTelefoneResidencial($telefoneResidencial);
    }

    public function getTelefoneResidencial()
    {
        $this->__load();
        return parent::getTelefoneResidencial();
    }

    public function setTelefoneComercial($telefoneComercial)
    {
        $this->__load();
        return parent::setTelefoneComercial($telefoneComercial);
    }

    public function getTelefoneComercial()
    {
        $this->__load();
        return parent::getTelefoneComercial();
    }

    public function setTelefoneCelular($telefoneCelular)
    {
        $this->__load();
        return parent::setTelefoneCelular($telefoneCelular);
    }

    public function getTelefoneCelular()
    {
        $this->__load();
        return parent::getTelefoneCelular();
    }

    public function setLogradouro($logradouro)
    {
        $this->__load();
        return parent::setLogradouro($logradouro);
    }

    public function getLogradouro()
    {
        $this->__load();
        return parent::getLogradouro();
    }

    public function setNumero($numero)
    {
        $this->__load();
        return parent::setNumero($numero);
    }

    public function getNumero()
    {
        $this->__load();
        return parent::getNumero();
    }

    public function setBairro($bairro)
    {
        $this->__load();
        return parent::setBairro($bairro);
    }

    public function getBairro()
    {
        $this->__load();
        return parent::getBairro();
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}